"""The plane: objects, the straightedge-and-compass instruction set, and exact
predicates over them."""

from .construct import (
    Figure,
    GeometryError,
    circle,
    circle_with_radius2,
    free_point,
    line,
    meet,
    meet_one,
    on_side,
    posit,
)
from .objects import Circle, Line, Point, midpoint_of, vector_between
from .predicates import (
    angle_cmp,
    angle_less,
    between,
    collinear,
    concurrent,
    congruent_sss,
    cross,
    distinct,
    dot,
    eq_angle,
    eq_area,
    eq_len,
    eq_polygon_area,
    eq_ratio,
    inside_circle,
    len2,
    on_circle,
    on_line,
    opposite_sides,
    parallel,
    perpendicular,
    polygon_area2,
    right_angle,
    same_side,
    signed_area2,
    similar,
)
from .trace import Claim, IntersectionEvent, Move, PredicateEvent, Trace, current_trace

__all__ = [
    "Circle",
    "Claim",
    "Figure",
    "GeometryError",
    "IntersectionEvent",
    "Line",
    "Move",
    "Point",
    "PredicateEvent",
    "Trace",
    "angle_cmp",
    "angle_less",
    "between",
    "circle",
    "circle_with_radius2",
    "collinear",
    "concurrent",
    "congruent_sss",
    "cross",
    "current_trace",
    "distinct",
    "dot",
    "eq_angle",
    "eq_area",
    "eq_len",
    "eq_polygon_area",
    "eq_ratio",
    "free_point",
    "inside_circle",
    "len2",
    "line",
    "meet",
    "meet_one",
    "midpoint_of",
    "on_circle",
    "on_line",
    "on_side",
    "opposite_sides",
    "parallel",
    "perpendicular",
    "polygon_area2",
    "posit",
    "right_angle",
    "same_side",
    "signed_area2",
    "similar",
    "vector_between",
]
